name: Testing

# Trigger on pushes, PRs (excluding documentation changes), and nightly.
on:
  push:
  pull_request:
permissions:
  contents: read

# Always force the use of Go modules
env:
  GO111MODULE: on

jobs:
  # Run the main gRPC-Go tests.
  tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: tests
            goversion: '1.22'

          - type: tests
            goversion: '1.22'
            testflags: -race

          - type: tests
            goversion: '1.22'
            testflags: -race -tags=buffer_pooling

          - type: tests
            goversion: '1.22'
            goarch: 386

          - type: tests
            goversion: '1.22'
            goarch: arm64

          - type: tests
            goversion: '1.21'

          - type: tests
            goversion: '1.22'
            testflags: -race
            grpcenv: GRPC_EXPERIMENTAL_ENABLE_NEW_PICK_FIRST=true

    steps:
      # Setup the environment.
      - name: Setup GOARCH
        if: matrix.goarch != ''
        run: echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Setup qemu emulator
        if: matrix.goarch == 'arm64'
        # setup qemu-user-static emulator and register it with binfmt_misc so that aarch64 binaries
        # are automatically executed using qemu.
        run: docker run --rm --privileged multiarch/qemu-user-static:7.2.0-1 --reset --credential yes --persistent yes

      - name: Setup GRPC environment
        if: matrix.grpcenv != ''
        run: echo "${{ matrix.grpcenv }}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goversion }}
          cache-dependency-path: '**/*go.sum'

      - name: Run tests
        if: matrix.type == 'tests'
        run: |
          go version
          go test ${{ matrix.testflags }} -cpu 1,4 -timeout 7m google.golang.org/grpc/...
          cd "${GITHUB_WORKSPACE}"
          for MOD_FILE in $(find . -name 'go.mod' | grep -Ev '^\./go\.mod|/security/advancedtls/'); do
            pushd "$(dirname ${MOD_FILE})"
            go test ${{ matrix.testflags }} -cpu 1,4 -timeout 2m ./...
            popd
          done
